import { openDb } from '../../lib/db';
import { upsertSyncedItem, createAdhocItem, setStatus, setParked, setTodayDate, setSnoozedUntil } from '../../lib/items-repo';
import { addPlanItem, setPlanItemEstimate, upsertPlan, reorderPlanItems } from '../../lib/plans-repo';
import { setSetting } from '../../lib/settings-repo';
import { localDateString, addDays } from '../../lib/date';
import { SETTINGS_KEYS } from '../../lib/config';
import type { NewSyncedItemInput } from '../../lib/types';

// Fictional data for the README screenshots. Everything here is invented --
// no real repo, work item, or person -- so the images can be regenerated by
// anyone without pointing Ariadne at a live GitHub/Azure DevOps account.
//
// Every state below is one the app can actually reach on its own (a merged PR
// Ariadne can't close itself, a paused item, an item worked on this morning
// and put back in the queue), so the screenshots show the real product rather
// than an arrangement only a seed script could produce.

const HOUR = 3_600_000;
const DAY = 24 * HOUR;

function iso(now: Date, msAgo: number): string {
  return new Date(now.getTime() - msAgo).toISOString();
}

// Keeps "earlier today" timestamps inside today, whatever time of day the
// script happens to run at -- a log that slips into yesterday would silently
// drop out of Today's logged total.
function earlierToday(now: Date, msAgo: number): string {
  const midnight = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 5);
  const target = new Date(now.getTime() - msAgo);
  return (target < midnight ? midnight : target).toISOString();
}

let externalIdCounter = 1000;

export function seedScreenshotData(dbPath: string, now = new Date()): void {
  const db = openDb(dbPath);
  const today = localDateString(now);

  const synced = (input: Omit<NewSyncedItemInput, 'externalId'>) =>
    upsertSyncedItem(db, { ...input, externalId: String(externalIdCounter++) });

  try {
    const sprintName = 'Sprint 14';
    setSetting(db, SETTINGS_KEYS.sprintName, sprintName);
    setSetting(db, SETTINGS_KEYS.sprintStart, addDays(today, -8));
    setSetting(db, SETTINGS_KEYS.sprintEnd, addDays(today, 6));
    setSetting(db, SETTINGS_KEYS.adoOrg, 'demo-org');
    setSetting(db, SETTINGS_KEYS.adoProject, 'Payments');
    setSetting(db, SETTINGS_KEYS.adoTeam, 'Payments Team');
    // Only their presence matters: it's what tells the dashboard this isn't a
    // first run. Nothing in this script ever calls out to either API.
    setSetting(db, SETTINGS_KEYS.githubPat, 'demo-token-not-real');
    setSetting(db, SETTINGS_KEYS.adoPat, 'demo-token-not-real');

    const insertSync = db.prepare('INSERT INTO sync_log (source, ran_at, item_count, error) VALUES (?, ?, ?, ?)');
    insertSync.run('github', iso(now, 3 * 60_000), 11, null);
    insertSync.run('ado', iso(now, 3 * 60_000), 8, null);

    // --- Today: three things picked for the day, in hand-picked order -------
    const stripeDoubleCharge = synced({
      source: 'github_pr',
      title: 'Fix double-charge on retried Stripe webhook',
      url: 'https://example.test/pr/1',
      reason: 'review_requested',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 6 * HOUR),
      prStatus: 'ready_for_review',
      hasUnresolvedConversations: true,
      repo: 'checkout-service',
    });
    const auditLogStorage = synced({
      source: 'ado_workitem',
      title: 'Migrate audit log storage to blob containers',
      url: 'https://example.test/ado/1',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, DAY),
      adoStatus: 'Active',
      repo: null,
    });
    const incidentTimeline = createAdhocItem(db, {
      title: "Write up the incident timeline for yesterday's payments outage",
      category: 'Teams',
    });

    upsertPlan(db, today, {});
    for (const [item, estimate] of [
      [stripeDoubleCharge, 90],
      [auditLogStorage, 120],
      [incidentTimeline, 45],
    ] as const) {
      setTodayDate(db, item.id, today);
      addPlanItem(db, today, item.id);
      setPlanItemEstimate(db, today, item.id, estimate);
    }
    reorderPlanItems(db, today, [stripeDoubleCharge.id, auditLogStorage.id, incidentTimeline.id]);

    // Worked on this morning, then put back in the queue -- which is why
    // Today's top row already has time against it without being started.
    const insertLog = db.prepare(
      'INSERT INTO time_logs (item_id, started_at, ended_at, duration_hours, note) VALUES (?, ?, ?, ?, ?)'
    );
    insertLog.run(
      stripeDoubleCharge.id,
      earlierToday(now, 3 * HOUR),
      earlierToday(now, 2 * HOUR + 15 * 60_000),
      0.75,
      'Reproduced the duplicate charge locally'
    );

    // --- In progress -------------------------------------------------------
    const retryBackoff = synced({
      source: 'github_pr',
      title: 'Add retry backoff to the payment webhook consumer',
      url: 'https://example.test/pr/2',
      reason: 'authored',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 2 * DAY),
      prStatus: 'ready_for_review',
      hasUnresolvedConversations: true,
      repo: 'checkout-service',
    });
    setStatus(db, retryBackoff.id, 'in_progress');
    // The one thing actually being worked on right now, so the top bar has a
    // live timer on it.
    insertLog.run(retryBackoff.id, iso(now, 34 * 60_000), null, null, null);

    const bulkExport = synced({
      source: 'ado_workitem',
      title: 'Support bulk export for audit logs',
      url: 'https://example.test/ado/2',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 3 * DAY),
      adoStatus: 'Active',
      repo: null,
    });
    setStatus(db, bulkExport.id, 'in_progress');

    // Paused: started, then deliberately set down.
    const digestEmails = synced({
      source: 'github_pr',
      title: 'Move digest emails to the new templating engine',
      url: 'https://example.test/pr/3',
      reason: 'authored',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, 9 * DAY),
      prStatus: 'draft',
      repo: 'notifications-api',
    });
    setStatus(db, digestEmails.id, 'in_progress');
    setParked(db, digestEmails.id, true);

    const reconciliationCron = synced({
      source: 'ado_workitem',
      title: 'Spike: replace the nightly reconciliation cron',
      url: 'https://example.test/ado/3',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, 12 * DAY),
      adoStatus: 'To Do',
      repo: null,
    });
    setStatus(db, reconciliationCron.id, 'in_progress');
    setParked(db, reconciliationCron.id, true);

    // --- Signals: waiting on you ------------------------------------------
    synced({
      source: 'github_pr',
      title: 'Reconcile invoice totals after the currency rounding fix',
      url: 'https://example.test/pr/4',
      reason: 'approved_unmerged',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 7 * DAY),
      prStatus: 'approved',
      repo: 'billing-worker',
    });
    synced({
      source: 'github_pr',
      title: 'Drop the legacy webhook signature check',
      url: 'https://example.test/pr/5',
      reason: 'review_requested',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, DAY),
      prStatus: 'ready_for_review',
      repo: 'checkout-service',
    });
    synced({
      source: 'ado_workitem',
      title: 'Confirm the 90-day retention policy for export archives',
      url: 'https://example.test/ado/4',
      reason: 'mention',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 2 * DAY),
      adoStatus: 'To Do',
      repo: null,
    });

    // --- Signals: blocked --------------------------------------------------
    synced({
      source: 'ado_workitem',
      title: 'Design review: multi-region failover plan',
      url: 'https://example.test/ado/5',
      reason: 'assigned',
      dueDate: addDays(today, 1),
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 2 * DAY),
      adoStatus: 'Blocked',
      repo: null,
    });

    // --- Signals: moving without you --------------------------------------
    synced({
      source: 'github_pr',
      title: 'Bump the Node runtime to 22 across the payments services',
      url: 'https://example.test/pr/6',
      reason: 'stale_own_pr',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, 11 * DAY),
      prStatus: 'ready_for_review',
      repo: 'platform-infra',
    });
    // Merged upstream while Ariadne still has it open: Ariadne is read-only,
    // so all it can do is say so and offer Complete.
    synced({
      source: 'github_pr',
      title: 'Add idempotency keys to the payment retry path',
      url: 'https://example.test/pr/7',
      reason: 'authored',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 4 * DAY),
      prStatus: 'merged',
      repo: 'checkout-service',
    });

    // --- Signals: lower priority ------------------------------------------
    synced({
      source: 'ado_workitem',
      title: 'Add dashboards for the new queue metrics',
      url: 'https://example.test/ado/6',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 3 * DAY),
      adoStatus: 'Done',
      repo: null,
    });
    createAdhocItem(db, {
      title: 'Follow up with the platform team about the shared queue quota',
      category: 'Face-to-face',
    });
    synced({
      source: 'ado_workitem',
      title: 'Write the runbook for manual payout replays',
      url: 'https://example.test/ado/7',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, 4 * DAY),
      adoStatus: 'To Do',
      repo: null,
    });

    // --- Snoozed: still there, just quiet ----------------------------------
    const metricsRename = synced({
      source: 'github_pr',
      title: 'Rename the internal metrics package',
      url: 'https://example.test/pr/8',
      reason: 'review_requested',
      dueDate: null,
      sprintIteration: null,
      rawUpdatedAt: iso(now, 5 * DAY),
      prStatus: 'ready_for_review',
      repo: 'platform-infra',
    });
    setSnoozedUntil(db, metricsRename.id, new Date(now.getTime() + DAY).toISOString());

    // --- Finished work: only visible in the sprint counter -----------------
    const retryMetric = synced({
      source: 'github_pr',
      title: 'Emit a metric for webhook retry exhaustion',
      url: 'https://example.test/pr/9',
      reason: 'authored',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 2 * DAY),
      prStatus: 'merged',
      repo: 'checkout-service',
    });
    setStatus(db, retryMetric.id, 'done', iso(now, DAY));

    const auditBackfill = synced({
      source: 'ado_workitem',
      title: 'Backfill the export audit trail',
      url: 'https://example.test/ado/8',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 3 * DAY),
      adoStatus: 'Done',
      repo: null,
    });
    setStatus(db, auditBackfill.id, 'done', iso(now, 2 * DAY));

    const queueDepthAlert = synced({
      source: 'ado_workitem',
      title: 'Add the queue depth alert',
      url: 'https://example.test/ado/9',
      reason: 'assigned',
      dueDate: null,
      sprintIteration: sprintName,
      rawUpdatedAt: iso(now, 4 * DAY),
      adoStatus: 'Ready for validation',
      repo: null,
    });
    setStatus(db, queueDepthAlert.id, 'done', iso(now, 3 * DAY));

    const pairingSession = createAdhocItem(db, {
      title: 'Pair with the data team on the reconciliation query',
      category: 'Face-to-face',
    });
    setStatus(db, pairingSession.id, 'done', earlierToday(now, 4 * HOUR));
  } finally {
    db.close();
  }
}

// Playwright starts the dev server before any test code runs, so the server
// already holds an open connection to this file -- deleting the file would
// leave it reading an unlinked inode. Empty the tables instead, which the
// server sees straight away.
export function resetScreenshotData(dbPath: string): void {
  const db = openDb(dbPath);
  try {
    for (const table of ['plan_items', 'plans', 'time_logs', 'item_links', 'items', 'sync_log', 'settings']) {
      db.prepare(`DELETE FROM ${table}`).run();
    }
  } finally {
    db.close();
  }
}
